#!/bin/sh

echo "Running Pre-commit Checks..."

# Verifica arquivos alterados
STAGED_FILES=$(git diff --cached --name-only)

if [ -z "$STAGED_FILES" ]; then
    echo "No files in the stage. Commit enabled."
    exit 0
fi

#Verifica alterações no Front
CHANGES_FRONT=$(echo "$STAGED_FILES" | grep '^front-end/')

if [ -n "$CHANGES_FRONT" ]; then
    echo "Running frontend Linters"
    cd front-end
    npm run lint
    
    if [ $? -ne 0 ]; then
        echo "Frontend Lint failed. Please fix issues before commit"
        exit 1
    fi
    echo "Frontend lint passed"
    
    echo "Running frontend unit tests"
    
    npm test -- --run
    
    FRONT_STATUS=$?
    cd ..

    if [ $FRONT_STATUS -ne 0 ]; then
        echo "Frontend unit tests failed. Please fix them before commit"
        exit 1
    fi
    echo "Frontend tests passed successfully"
else
    echo "No frontend changes"
fi

#Verifica alterações de backend
CHANGES_BACKEND=$(echo "$STAGED_FILES" | grep '^back-end/')

if [ -n "$CHANGES_BACKEND" ]; then
    echo "Running backend linters (Checkstyle)"
    cd back-end
    if [ -f "./mvnw.cmd" ] && [ -n "$COMSPEC" ]; then
        MVN_CMD="./mvnw.cmd"
    else
        chmod +x ./mvnw
        MVN_CMD="./mvnw"
    fi
    $MVN_CMD checkstyle:check
    if [ $? -ne 0 ]; then
        echo "Backend Lint failed. Please fix code issues before commit"
        exit 1
    fi
    echo "Backend Checkstyle passed"
    echo "Running backend unit tests"
    cd back-end
    if [ -f "./mvnw.cmd" ] && [ -n "$COMSPEC" ]; then
        ./mvnw.cmd test
    else
        chmod +x ./mvnw
        ./mvnw test
    fi
    BACK_STATUS=$?
    cd ..

    if [ $BACK_STATUS -ne 0 ]; then
        echo "Backend unit tests failed. Please fix them before commit"
        exit 1
    fi
    echo "Backend tests passed successfully"
else
    echo "No backend changes"
fi

echo "Commit passed all quality checks"
exit 0