# Profile: Prod (Production with PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Security: Disable H2 console in production
spring.h2.console.enabled=false

# More restricted logs for production
logging.level.root=WARN
logging.level.com.pms.calprop=INFO
