# Profile: UAT (User Acceptance Testing / CI)
spring.datasource.url=${DB_URL_UAT:jdbc:h2:mem:calcprop_uat}
spring.datasource.username=${DB_USER_UAT:admin}
spring.datasource.password=${DB_PASS_UAT:admin}

# Mantém o H2 para CI, mas permite troca via Env Vars
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logs mais detalhados para depuração em UAT
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.pms.calprop=DEBUG
