# Profile: Prod (Production with H2 in File)
# Persistent H2 database configuration saved to a local file to prevent instant data loss upon restarts
spring.datasource.url=jdbc:h2:file:./data/calcpropdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Security: Disable H2 console in production
spring.h2.console.enabled=false

# More restricted logs for production
logging.level.root=WARN
logging.level.com.pms.calprop=INFO
