# Profile: Main (Production)
# Aqui é OBRIGATÓRIO passar as variáveis de ambiente no servidor real
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

# Configurações de Banco Real (ex: PostgreSQL/MySQL)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Desabilita console H2 por segurança em produção
spring.h2.console.enabled=false

# Nível de log mais restrito para performance
logging.level.root=INFO
logging.level.com.pms.calprop=INFO
